# Generated by Django 5.1.2 on 2024-11-22 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0006_certificado'),
        ('core', '0010_delete_audituser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('PayPal', 'PayPal')], max_length=50, verbose_name='Método de Pago')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('costo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attention.costosatencion', verbose_name='Costo Atención')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
